"""add_branding_to_tenant

Revision ID: 4632e8bd4582
Revises: e6d9429008c5
Create Date: 2026-03-21 23:09:30.244658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4632e8bd4582'
down_revision: Union[str, Sequence[str], None] = 'e6d9429008c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_service_time_seconds', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branding', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('branding')

    with op.batch_alter_table('queue_configs', schema=None) as batch_op:
        batch_op.drop_column('avg_service_time_seconds')

    # ### end Alembic commands ###
