"""add_superadmin_suspended_audit_log

Revision ID: 762c6be3b174
Revises: f2ad2bab7c15
Create Date: 2026-03-22 11:15:04.458055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762c6be3b174'
down_revision: Union[str, Sequence[str], None] = 'f2ad2bab7c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_tenant_id', sa.String(length=36), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['b2b_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_target_tenant_id'), ['target_tenant_id'], unique=False)

    with op.batch_alter_table('b2b_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superadmin', sa.Boolean(), server_default='false', nullable=False))

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_suspended', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_suspended')

    with op.batch_alter_table('b2b_users', schema=None) as batch_op:
        batch_op.drop_column('is_superadmin')

    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_target_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_admin_user_id'))

    op.drop_table('admin_audit_logs')
    # ### end Alembic commands ###
