"""initial_schema

Revision ID: e6d9429008c5
Revises: 
Create Date: 2026-03-10 21:58:20.147177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d9429008c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_name'), ['name'], unique=False)

    op.create_table('b2b_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('b2b_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_b2b_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_b2b_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('queue_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('form_schema', sa.JSON(), nullable=False),
    sa.Column('qr_rotation_enabled', sa.Boolean(), nullable=False),
    sa.Column('qr_rotation_interval', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queue_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queue_configs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('queue_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('queue_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['queue_id'], ['queue_configs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queue_entries_queue_id'), ['queue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_entries_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_entries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_queue_entries_queue_id'))

    op.drop_table('queue_entries')
    with op.batch_alter_table('queue_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_configs_tenant_id'))

    op.drop_table('queue_configs')
    with op.batch_alter_table('b2b_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_b2b_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_b2b_users_email'))

    op.drop_table('b2b_users')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_name'))

    op.drop_table('tenants')
    # ### end Alembic commands ###
