"""add_called_at_to_queue_entry

Revision ID: f2ad2bab7c15
Revises: 4632e8bd4582
Create Date: 2026-03-22 11:04:00.378279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ad2bab7c15'
down_revision: Union[str, Sequence[str], None] = '4632e8bd4582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('called_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.drop_column('called_at')

    # ### end Alembic commands ###
